### ISSUE TITLE
tvOS: MGM Apple TV app - Load of 30 requests/ sec causes some requests to fail.

### ISSUE THREAD

**Issue by elv-arun** [eluv-io/elv-tvos-sample-site#7]
endpoints tested:
curl https://tvos-srv.contentfabric.io/redeemsite.hbs/main/L7BAX95T
curl https://tvos-srv.contentfabric.io/redeemwatch.hbs/main/L7BAX95T

Upto 25 requests/s response received successfully.
At 30 requests/s some requests fail

> echo "GET https://tvos-srv.contentfabric.io/redeemsite.hbs/main/L7BAX95T" | vegeta attack -duration=5s -rate=30 | vegeta report
> Requests      [total, rate, throughput]         150, 30.23, 2.49
> Duration      [total, attack, wait]             34.933s, 4.962s, 29.971s
> Latencies     [min, mean, 50, 90, 95, 99, max]  23.493s, 29.052s, 29.761s, 30.003s, 30.004s, 30.005s, 30.005s
> Bytes In      [total, mean]                     208278, 1388.52
> Bytes Out     [total, mean]                     0, 0.00
> Success       [ratio]                           58.00%
> Status Codes  [code:count]                      0:63  200:87
> Error Set:
> Get "https://tvos-srv.contentfabric.io/redeemsite.hbs/main/L7BAX95T": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> Get "https://tvos-srv.contentfabric.io/redeemsite.hbs/main/L7BAX95T": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by elv-wayne** [comment]
Fixed in https://github.com/eluv-io/elv-tvos-sample-site/commit/fcac85c0648ab41e3479625abcbc12dab2dee609

Added mutex for redeeming the same code. The first redemption will cache allowing fast access for subsequent requests of the same code until a refresh from the server.

Also limited 500 max concurrent requests with a semaphore.
